version: '3.9'

services:

  web:
    container_name: odoo_web
    image: odoo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo_db
      - USER=developer
      - PASSWORD=123456
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize

  db:
    container_name: odoo_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=lachua
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=developer
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      
volumes:
  odoo-db-data:
  odoo-web-data: