version: '3.9'

services:

  web:
    container_name: odoo_web
    image: odoo:latest
    depends_on: 
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo_db
      - USER=developer
      - PASSWORD=123456
  
  db:
    container_name: odoo_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=developer
